### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by pascal65536** [jeongmincho/anki-add-dialog-web-browser#1]
Hi, I'm a Linux Mint user. I want to deploy this project, but I get an error

```
    from PyQt5.QtNetwork import QLocalServer, QLocalSocket, QNetworkProxy  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libgssapi_krb5.so.2: cannot open shared object file: No such file or directory
```

Please post requirements.txt file

**Comment by jmhacks** [comment]
Hey @pascal65536, thanks for raising this issue. Have you tried downloading the add-on with the code `918010938`? 

Regarding your error, that happens because Linux needs an additional system library for Qt's network features. I believe you can fix it by running:

```bash
sudo apt-get install libkrb5-dev
```

No requirements.txt should be needed since this is an Anki addon - it uses Anki's built-in Qt libraries. Let me know if you still have issues after installing the library.

**Comment by jmhacks** [comment]
I'm able to successfully run the add-on on Linux Ubuntu by obtaining it directly through the app.
![Screenshot 2024-12-11 at 9 16 25 PM](https://github.com/user-attachments/assets/6ab936ef-97d7-4f94-8d39-e8709b83cf28)

**Comment by pascal65536** [comment]
Yeah, Science! 
Thank you

![Снимок экрана от 2024-12-12 20-23-46](https://github.com/user-attachments/assets/ee6a07ff-dd94-42b9-89a2-bc0d431fdba5)

**Comment by jmhacks** [comment]
Nice! Let me know if you run into any other issues. Will close this out for now.
